Add files via upload
오류 수정
     ,-[/vercel/path0/pages/dinner/jamsil/restaurant/[name].js:128:1]
 128 |       return { emoji:'🌧️🥣', lines:[
 129 |         '비가 추적추적, 발도 무겁고 배도 고프고.',
 130 |         `${name} 뚝배기 앞에 앉으면 그제야 숨이 쉬어집니다.`,
 131 |         '첫 국물 한 숟갈에 "아, 살겠다" 소리가 절로 나오는 그 맛.`,
     :         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 132 |       ]}
 133 |     }
 134 |     return { emoji:'🥣', lines:[
     `----
Caused by:
    Syntax Error
Import trace for requested module:
./pages/dinner/jamsil/restaurant/[name].js
> Build failed because of webpack errors
Error: Command "npm run build" exited with 1